# -*- coding: utf-8 -*-

# execution.py

from abc import ABCMeta, abstractmethod
import datetime
import queue

from Backtest_Engine.event import FillEvent, OrderEvent

class ExecutionHandler(object):
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market.

    The handlers can be used to subclass simulated brokerages
    or live brokerages, with identical interfaces. This allows
    strategies to be backtested in a very similar manner to the
    live trading engine.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def execute_order(self, event):
        """
        Takes an Order event and executes it, providing
        a Fill event that gets placed onto the Events queue.

        :param event: Contains an Event object with order information.
        :return:
        """
        raise NotImplementedError("Should implement execute_order()")

class SimulatedExecutionHandler(ExecutionHandler):
    """
    The simulated execution handler simply converts all order
    objects into their equivalent fill objects automatically
    without latency, slippage or fill-ratio issues.

    This allows a straightforward "first go" test of any strategy,
    before implementation with a more sophisticated execution
    handler.
    """

    def __init__(self, events):
        """
        Initializes the handler, setting the event queues
        up internally.

        :param events: The Queue of Event objects.
        """
        self.events = events

    def execute_order(self, event):
        """
        Simply converts Order objects into Fill objects naively,
        i.e., without any latency, slippage or fill ration problems.

        :param event: Contains an Event object with order information.
        :return:
        """
        if event.type == 'ORDER':
            fill_event = FillEvent(datetime.datetime.utcnow(),
                                   event.symbol, 'CHINA',
                                   event.quantity, event.direction,
                                   None)
            self.events.put(fill_event)